// Quotes for the opening line beside Continue reading (see quotes.js).
// Public-domain books only, each with its author and the work it's from.
// Keep them short: about three lines at most beside the hero. A "\n" breaks a
// line of verse.
window.QUOTE_LIST = [
  { text: 'There is no Frigate like a Book\nTo take us Lands away', author: 'Emily Dickinson' },
  { text: 'I declare after all there is no enjoyment like reading!', author: 'Jane Austen', source: 'Pride and Prejudice' },
  { text: 'Simplify, simplify.', author: 'Henry David Thoreau', source: 'Walden' },
  { text: 'The earth laughs in flowers.', author: 'Ralph Waldo Emerson', source: 'Hamatreya' },
  { text: 'It is not down in any map; true places never are.', author: 'Herman Melville', source: 'Moby-Dick' },
  { text: 'A thing of beauty is a joy for ever.', author: 'John Keats', source: 'Endymion' },
  { text: 'Heaven is under our feet as well as over our heads.', author: 'Henry David Thoreau', source: 'Walden' },
  { text: 'I would always rather be happy than dignified.', author: 'Charlotte Brontë', source: 'Jane Eyre' },
  { text: 'I like good strong words that mean something.', author: 'Louisa May Alcott', source: 'Little Women' },
  { text: 'I am not afraid of storms, for I am learning how to sail my ship.', author: 'Louisa May Alcott', source: 'Little Women' },
  { text: 'Though she be but little, she is fierce.', author: 'William Shakespeare', source: 'A Midsummer Night’s Dream' },
  { text: 'There is nothing like staying at home for real comfort.', author: 'Jane Austen', source: 'Emma' },
  { text: 'If you look the right way, you can see that the whole world is a garden.', author: 'Frances Hodgson Burnett', source: 'The Secret Garden' },
  { text: 'Isn’t it nice to think that tomorrow is a new day with no mistakes in it yet?', author: 'L. M. Montgomery', source: 'Anne of Green Gables' },
  { text: 'I’m so glad I live in a world where there are Octobers.', author: 'L. M. Montgomery', source: 'Anne of Green Gables' },
  { text: 'Why, sometimes I’ve believed as many as six impossible things before breakfast.', author: 'Lewis Carroll', source: 'Through the Looking-Glass' },
  { text: 'To travel hopefully is a better thing than to arrive.', author: 'Robert Louis Stevenson', source: 'El Dorado' },
  { text: 'The years teach much which the days never know.', author: 'Ralph Waldo Emerson', source: 'Experience' },
  { text: 'Nature always wears the colors of the spirit.', author: 'Ralph Waldo Emerson', source: 'Nature' },
  { text: 'Come forth into the light of things,\nLet Nature be your teacher.', author: 'William Wordsworth', source: 'The Tables Turned' },
  { text: 'The world is so full of a number of things,\nI’m sure we should all be as happy as kings.', author: 'Robert Louis Stevenson', source: 'A Child’s Garden of Verses' },
  { text: 'Read the best books first, or you may not have a chance to read them at all.', author: 'Henry David Thoreau', source: 'A Week on the Concord and Merrimack Rivers' },
  { text: 'We have all a better guide in ourselves, if we would attend to it, than any other person can be.', author: 'Jane Austen', source: 'Mansfield Park' },
  { text: 'What do we live for, if it is not to make life less difficult to each other?', author: 'George Eliot', source: 'Middlemarch' },
  { text: 'Dear old world, you are very lovely, and I am glad to be alive in you.', author: 'L. M. Montgomery', source: 'Anne of Green Gables' },
  { text: 'Where you tend a rose, my lad, a thistle cannot grow.', author: 'Frances Hodgson Burnett', source: 'The Secret Garden' },
  { text: 'How far that little candle throws his beams!\nSo shines a good deed in a naughty world.', author: 'William Shakespeare', source: 'The Merchant of Venice' },
  { text: 'To see a World in a Grain of Sand\nAnd a Heaven in a Wild Flower', author: 'William Blake', source: 'Auguries of Innocence' },
  { text: 'Hope is the thing with feathers\nThat perches in the soul', author: 'Emily Dickinson' },
  { text: 'The sun is but a morning star.', author: 'Henry David Thoreau', source: 'Walden' },
  { text: 'Afoot and light-hearted I take to the open road.', author: 'Walt Whitman', source: 'Song of the Open Road' },
  { text: 'Begin at the beginning, and go on till you come to the end: then stop.', author: 'Lewis Carroll', source: 'Alice’s Adventures in Wonderland' },
  { text: 'We are all in the gutter, but some of us are looking at the stars.', author: 'Oscar Wilde', source: 'Lady Windermere’s Fan' },
  { text: 'The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.', author: 'Jane Austen', source: 'Northanger Abbey' },
  { text: 'Life is made of ever so many partings welded together.', author: 'Charles Dickens', source: 'Great Expectations' },
  { text: 'How many a man has dated a new era in his life from the reading of a book.', author: 'Henry David Thoreau', source: 'Walden' },
  { text: 'I exist as I am, that is enough.', author: 'Walt Whitman', source: 'Song of Myself' },
  { text: 'There is nothing either good or bad, but thinking makes it so.', author: 'William Shakespeare', source: 'Hamlet' },
  { text: 'I am no bird; and no net ensnares me.', author: 'Charlotte Brontë', source: 'Jane Eyre' },
  { text: 'Heaven knows we need never be ashamed of our tears.', author: 'Charles Dickens', source: 'Great Expectations' },
  { text: 'Forever is composed of Nows.', author: 'Emily Dickinson' },
  { text: 'One cannot have too large a party.', author: 'Jane Austen', source: 'Emma' },
];
